config/routes.rb
Rails.application.routes.draw do
  # resources :interventions

  # Authenticate user to use intervention
  authenticate :user, ->(user) { user.superadmin_role? or user.employee_role? } do
    get "/interventions" => "interventions#index"
  end
  # get "/interventions" => "interventions#index"
  post "/interventions" => "interventions#create"


  get "/get_buildings/:customer_id", to: "interventions#get_buildings"
  get "/get_batteries/:building_id", to: "interventions#get_batteries"
  get "/get_columns/:battery_id", to: "interventions#get_columns"
  get "/get_elevators/:column_id", to: "interventions#get_elevators"
  
  devise_for :users
  
  resources :quotes
  resources :leads
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Authenticates Blazer Using Devise
  authenticate :user, ->(user) { user.superadmin_role? } do
    mount Blazer::Engine, at: "blazer"
  end

  # # If Above Doesn't Work Then Uncomment Below:
  # mount Blazer::Engine, at: "blazer"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get "residential" => "pages#residential"
  get "commercial" => "pages#commercial"
  get "quotes" => "pages#quote"
  

  get "/index" => "pages#index"

  # /quotes is the action from the form in quote.html.erb
  post "/quotes" => "quotes#create"

  # /leads is the action from the form in index.html.erb
  post "/leads" => "leads#create"

  # match '/watson'     => 'watson#speak', via: :get
  get '/watson/update' => 'watson#speak'
 
   
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_footer.html.erb
<!-- FOOTER -->	
<footer id="footer">
		<div class="container">
			<div class="row">
				<!-- col #1 -->
				<div class="col-md-8">

					<div class="footer-logo">
						<%= image_tag("Rocket_Elevator_Assets/R2logo.png") %>
					</div>
					<h3 class="letter-spacing-1">WHY US?</h3>

					<!-- Small Description -->
					<p>
						We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have
					</p>
					<h2>(418) 555-1234</h2>
				</div>
				<!-- /col #1 -->
				
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				<ul class="float-right m-0 list-inline mobile-block">
					<li><a href="#">Terms &amp; Conditions</a></li>
					<li>&bull;</li>
					<li><a href="#">Privacy</a></li>
				</ul>
				&copy; All Rights Reserved, Company LTD
			</div>
		</div>
</footer>
<!-- /FOOTER -->

app/views/parts/_header.html.erb
        
<!-- TOP NAV -->
<div id="header" class="navbar-toggleable-md sticky transparent clearfix">			
    <header id="topNav">
        <div class="container">

            <!-- Mobile Menu Button -->
            <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Logo -->
            <a class="logo float-left" href="/#">
                <%= image_tag 'Rocket_Elevator_Assets/R2', alt: 'Rocket Elevators' %>
            </a>
            <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                <nav class="nav-main">
                    <ul id="topMain" class="nav nav-pills nav-main ">
                        <li class="active"><!-- HOME -->
                            <%= link_to "HOME", root_path, 'data-turbolinks': false%>
                        </li>
                        <li><!-- SERVICES -->										
                            <a class ='dropdown-toggle'>SERVICES</a>
                            <ul class='dropdown-menu white-space= normal'>
                                <li><%= link_to "All services", "#{root_path}#services", 'data-turbolinks': false%></li>
                                <li><a href="<%= residential_path %>">Residential</a></li>
                                <li><a href="<%= commercial_path %>">Commercial</a></li>
                                <li><a href="<%= quotes_path %>">Get a Submission</a></li>	
                            </ul>
                        </li>
                        <li><!-- PORTFOLIO -->
                            <%= link_to "PORTFOLIO", "#{root_path}#portfolio", 'data-turbolinks': false%>
                        </li>
                        <li><!-- NEWS -->
                            <%= link_to "NEWS", "#{root_path}#news", 'data-turbolinks': false%>
                        </li>
                        <li><!-- CLIENTS -->
                            <%= link_to "CLIENTS", "#{root_path}#clients", 'data-turbolinks': false%>	
                        </li>
                        <li><!-- CONTACT -->
                            <%= link_to "CONTACT", "#{root_path}#contact", 'data-turbolinks': false%>
                        </li>
                        <li><!-- INTERVENTION -->
                            <% if current_user and (current_user.superadmin_role? or current_user.employee_role?) %>
                                <%= link_to "INTERVENTION", interventions_path, 'data-turbolinks': false%>
                            <% end%>
                        </li>
                        <li class="dropdown"><!-- SERVICES -->
                            <a class="dropdown-toggle" href="#">
                                MY ACCOUNT
                            </a>
                            <ul class="dropdown-menu">
                                <% if !current_user %>
                                    <li><%= link_to "LOGIN", new_user_session_path %></li>
                                    <li><%= link_to "SIGN UP", new_user_registration_path %></li>
                                <% elsif current_user.superadmin_role? %>
                                    <li><%= link_to "BACKOFFICE", rails_admin_path %> </li>
                                    <li><%= link_to "PROFILE", edit_user_registration_path %></li>
                                    <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                                <% elsif current_user.employee_role? %>
                                    <li><%= link_to "BACKOFFICE", rails_admin_path %> </li>
                                    <li><%= link_to "PROFILE", edit_user_registration_path %></li>
                                    <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                                <% else %>
                                    <li><%= link_to "PROFILE", edit_user_registration_path %></li>
                                    <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></li>
                                <% end %>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</div>
<!-- /Top Nav -->