config/routes.rb
Rails.application.routes.draw do
  # resources :interventions

  # Authenticate user to use intervention
  authenticate :user, ->(user) { user.superadmin_role? or user.employee_role? } do
    get "/interventions" => "interventions#index"
  end
  # get "/interventions" => "interventions#index"
  post "/interventions" => "interventions#create"


  get "/get_buildings/:customer_id", to: "interventions#get_buildings"
  get "/get_batteries/:building_id", to: "interventions#get_batteries"
  get "/get_columns/:battery_id", to: "interventions#get_columns"
  get "/get_elevators/:column_id", to: "interventions#get_elevators"
  
  devise_for :users
  
  resources :quotes
  resources :leads
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Authenticates Blazer Using Devise
  authenticate :user, ->(user) { user.superadmin_role? } do
    mount Blazer::Engine, at: "blazer"
  end

  # # If Above Doesn't Work Then Uncomment Below:
  # mount Blazer::Engine, at: "blazer"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get "residential" => "pages#residential"
  get "commercial" => "pages#commercial"
  get "quotes" => "pages#quote"
  

  get "/index" => "pages#index"

  # /quotes is the action from the form in quote.html.erb
  post "/quotes" => "quotes#create"

  # /leads is the action from the form in index.html.erb
  post "/leads" => "leads#create"

  # match '/watson'     => 'watson#speak', via: :get
  get '/watson/update' => 'watson#speak'
 
   
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]

  # GET /interventions or /interventions.json
  def index
  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions or /interventions.json
  def create
    # @intervention = Intervention.new(intervention_params)
    @intervention = Intervention.new

    @intervention.author = current_user.employee.id
    @intervention.customer_id = params[:customers]
    @intervention.building_id = params[:buildings]
    @intervention.battery_id = params[:batteries] unless params[:columns] != ""
    @intervention.column_id = params[:columns] unless params[:elevators] != ""
    @intervention.elevator_id = params[:elevators]
    @intervention.employee_id = params[:employees]
    @intervention.result = "Incomplete"
    @intervention.report = params[:description]
    @intervention.status = "Pending"

    if @intervention.save!
      redirect_back fallback_location: root_path, notice: "Intervention Created"
    end

    client = ZendeskAPI::Client.new do |config|
        config.url = ENV['ZENDESK_URL']
        config.username = ENV['ZENDESK_USERNAME']
        config.token = ENV['ZENDESK_TOKEN']
    end

    ZendeskAPI::Ticket.create!(client, 
      :subject => "Intervention create by #{current_user.employee.first_name} #{current_user.employee.last_name}", 
      :comment => { 
        :value => "Requester: #{current_user.employee.first_name} #{current_user.employee.last_name}
                   Company Name: #{Customer.find(params[:customers]).company_name}
                   Building ID: #{params[:buildings]}
                   Battery ID: #{params[:batteries]}
                   Column ID: #{params[:columns]}
                   Elevator ID: #{params[:elevators]}
                   Assigned Employee: #{Employee.find(params[:employees]).first_name} #{Employee.find(params[:employees]).last_name}
                   Description: #{params[:description]}"
      }, 
      :requester => { 
          "name": "#{current_user.employee.first_name} #{current_user.employee.last_name}", 
          # "email": @lead.email 
      },
      :priority => "urgent",
      :type => "problem"
    )

    # respond_to do |format|
    #   if @intervention.save
    #     format.html { redirect_to @intervention, notice: "Intervention was successfully created." }
    #     format.json { render :show, status: :created, location: @intervention }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @intervention.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_buildings
    puts params[:customer_id]
    @buildings = Building.where(customer_id: params[:customer_id])

    respond_to do |format|
      format.json {render :json => @buildings}
    end
  end

  def get_batteries
    puts params[:building_id]
    @batteries = Battery.where(building_id: params[:building_id])

    respond_to do |format|
      format.json {render :json => @batteries}
    end
  end

  def get_columns
    puts params[:battery_id]
    @columns = Column.where(battery_id: params[:battery_id])

    respond_to do |format|
      format.json {render :json => @columns}
    end
  end

  def get_elevators
    puts params[:column_id]
    @elevators = Elevator.where(column_id: params[:column_id])

    respond_to do |format|
      format.json {render :json => @elevators}
    end
  end

  def course_search
    puts "Whatever"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_intervention
    @intervention = Intervention.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def intervention_params
    params.require(:intervention).permit(:author, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :start_date, :end_date, :result, :report, :status)
  end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.number_field :author %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :building_id %>
    <%= form.number_field :building_id %>
  </div>

  <div class="field">
    <%= form.label :battery_id %>
    <%= form.number_field :battery_id %>
  </div>

  <div class="field">
    <%= form.label :column_id %>
    <%= form.number_field :column_id %>
  </div>

  <div class="field">
    <%= form.label :elevator_id %>
    <%= form.number_field :elevator_id %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.number_field :employee_id %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.text_field :result %>
  </div>

  <div class="field">
    <%= form.label :report %>
    <%= form.text_area :report %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<html>

 <body class="smoothscroll enable-animation">
  <!-- wrapper -->
  <div id="wrapper">

    <!-- PAGE HEADER -->
    <section class="page-header page-header-xlg parallax parallax-4" style = "background-image: url(<%= asset_path("Rocket_Elevator_Assets/Quote/AdobeStock_556688421.jpg") %>)">
      <div class="overlay dark-4"><!-- dark overlay [1 to 9 opacity] --></div>

      <div class="container">

        <div class="bold font-raleway wow fadeInUp animated">
            <h2 class="fs-55 fw-400 text-center">INTERVENTIONS</h2>
        </div>

      </div>
    </section>
    <!-- /PAGE HEADER --> 

    <%# <div class="row no-gutters wow slideInUp" data-wow-duration="1s"> %>
    <div>
      <%# <div class="col-md-12 home-form"> %>

        <%= form_tag(interventions_path, method: "post", class: "container mt-50", remote: false) do %>
          <div class="form-group form-row">
            <div class="col-12 col-md" id="customer-group">
              <%= label_tag "customers", "Customer", class: "form-label" %>
              <%= select_tag "customers", options_from_collection_for_select(Customer.all, "id", "company_name"), prompt: "-- Required --", required: true, class: "form-control mb-0 mr-sm-0 mb-sm-0 border border-secondary text-dark" %>
            </div>
          </div>
          <div class="form-group form-row">
            <div class="col-12 col-md" id="building-group">
              <%= label_tag "buildings", "Building", class: "form-label" %>
              <%= select_tag "buildings", options_from_collection_for_select(Building.all, "id", "full_name_of_the_building_administrator"), prompt: "-- Required --", required: true, class: "form-control mb-0 mr-sm-0 mb-sm-0 border border-secondary text-dark" %>
            </div>
            <div class="col-12 col-md" id="battery-group">
              <%= label_tag "batteries", "Battery", class: "form-label" %>
              <%= select_tag "batteries", options_from_collection_for_select(Battery.all, "id", "id"), prompt: "-- Required --", required: true, class: "form-control mb-0 mr-sm-0 mb-sm-0 border border-secondary text-dark" %>
            </div>
            <div class="col-12 col-md" id="column-group">
              <%= label_tag "columns", "Column", class: "form-label" %>
              <%= select_tag "columns", options_from_collection_for_select(Column.all, "id", "id"), prompt: "-- None --", class: "form-control mb-0 mr-sm-0 mb-sm-0 border border-secondary text-dark" %>
            </div>
            <div class="col-12 col-md" id="elevator-group">
              <%= label_tag "elevators", "Elevator", class: "form-label" %>
              <%= select_tag "elevators", options_from_collection_for_select(Elevator.all, "id", "id"), prompt: "-- None --", class: "form-control mb-0 mr-sm-0 mb-sm-0 border border-secondary text-dark" %>
            </div>
          </div>
          <div class="form-group form-row">
            <div class="col" id="employee-group">
              <%= label_tag "employees", "Employee", class: "form-label" %>
              <%= select_tag "employees", options_from_collection_for_select(Employee.all, "id", "full_name"), prompt: "-- None --", class: "form-control mb-0 mr-sm-0 mb-sm-0 border border-secondary text-dark" %>
            </div>
          </div>
          <div class="form-group">
            <%= label_tag "description", "Intervention Description", class: "form-label" %>
            <%= text_area_tag "description", nil, required: true, class: "form-control h-150 border border-secondary" %>
          </div>
          <div class="form-group">
            <% if current_user and current_user.employee_role? %>
              <%= submit_tag("Submit Intervention", class: "btn btn-primary btn-block", title: "Hello") %>
            <% else %>
              <%= submit_tag("Submit Intervention", class: "btn btn-primary btn-block", disabled: true) %>
            <% end %>
          </div>
        <% end %>

      <%# </div> %>
    </div>


  <div>
  <!-- /wrapper -->

  <!-- SCROLL TO TOP -->
  <a href="#" id="toTop"></a>

  </body>
</html>

app/views/interventions/new.html.erb
<h1>New Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @intervention.author %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @intervention.customer_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @intervention.building_id %>
</p>

<p>
  <strong>Battery:</strong>
  <%= @intervention.battery_id %>
</p>

<p>
  <strong>Column:</strong>
  <%= @intervention.column_id %>
</p>

<p>
  <strong>Elevator:</strong>
  <%= @intervention.elevator_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @intervention.employee_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @intervention.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @intervention.end_date %>
</p>

<p>
  <strong>Result:</strong>
  <%= @intervention.result %>
</p>

<p>
  <strong>Report:</strong>
  <%= @intervention.report %>
</p>

<p>
  <strong>Status:</strong>
  <%= @intervention.status %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>